import type { BillingCycle } from "./types";

// Mock subscription services with realistic data
export const MOCK_SUBSCRIPTIONS = [
  {
    name: "Netflix Premium",
    cost: 19.99,
    currency: "USD",
    billingCycle: "monthly" as BillingCycle,
    category: "Entertainment",
    from: "billing@netflix.com",
    subject: "Your Netflix subscription receipt",
  },
  {
    name: "Spotify Premium",
    cost: 9.99,
    currency: "USD",
    billingCycle: "monthly" as BillingCycle,
    category: "Music",
    from: "noreply@spotify.com",
    subject: "Spotify Premium - Payment Confirmation",
  },
  {
    name: "Adobe Creative Cloud",
    cost: 54.99,
    currency: "USD",
    billingCycle: "monthly" as BillingCycle,
    category: "Software",
    from: "adobe@adobe.com",
    subject: "Adobe Creative Cloud Receipt",
  },
  {
    name: "GitHub Pro",
    cost: 4.0,
    currency: "USD",
    billingCycle: "monthly" as BillingCycle,
    category: "Development",
    from: "billing@github.com",
    subject: "GitHub Pro subscription renewed",
  },
  {
    name: "Figma Professional",
    cost: 12.0,
    currency: "USD",
    billingCycle: "monthly" as BillingCycle,
    category: "Design",
    from: "team@figma.com",
    subject: "Figma Professional Plan Receipt",
  },
  {
    name: "The New York Times",
    cost: 17.0,
    currency: "USD",
    billingCycle: "monthly" as BillingCycle,
    category: "News",
    from: "nytimes@nytimes.com",
    subject: "Your NYT Digital Subscription",
  },
  {
    name: "Notion Plus",
    cost: 8.0,
    currency: "USD",
    billingCycle: "monthly" as BillingCycle,
    category: "Productivity",
    from: "team@notion.so",
    subject: "Notion Plus Payment Received",
  },
  {
    name: "Dropbox Plus",
    cost: 11.99,
    currency: "USD",
    billingCycle: "monthly" as BillingCycle,
    category: "Storage",
    from: "no-reply@dropbox.com",
    subject: "Dropbox Plus - Monthly Receipt",
  },
  {
    name: "ChatGPT Plus",
    cost: 20.0,
    currency: "USD",
    billingCycle: "monthly" as BillingCycle,
    category: "AI",
    from: "noreply@openai.com",
    subject: "ChatGPT Plus subscription confirmation",
  },
  {
    name: "AWS Services",
    cost: 45.32,
    currency: "USD",
    billingCycle: "monthly" as BillingCycle,
    category: "Cloud",
    from: "aws-billing@amazon.com",
    subject: "AWS Monthly Bill",
  },
];

// Mock domain registrations
export const MOCK_DOMAINS = [
  {
    domainName: "myawesomeapp.com",
    registrar: "Namecheap",
    cost: 12.98,
    currency: "USD",
    from: "domains@namecheap.com",
    subject: "Domain Registration Confirmation - myawesomeapp.com",
  },
  {
    domainName: "startupidea.io",
    registrar: "GoDaddy",
    cost: 29.99,
    currency: "USD",
    from: "noreply@godaddy.com",
    subject: "GoDaddy Domain Registration Receipt",
  },
  {
    domainName: "portfolio-site.dev",
    registrar: "Google Domains",
    cost: 12.0,
    currency: "USD",
    from: "domains-noreply@google.com",
    subject: "Google Domains: Registration Confirmation",
  },
  {
    domainName: "coolproject.xyz",
    registrar: "Cloudflare",
    cost: 9.15,
    currency: "USD",
    from: "noreply@cloudflare.com",
    subject: "Cloudflare Registrar - Domain Registered",
  },
  {
    domainName: "business-site.co",
    registrar: "Hover",
    cost: 17.99,
    currency: "USD",
    from: "support@hover.com",
    subject: "Hover Domain Registration",
  },
];
